// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJqTNdoyNZ95ijwdto7MJ3Rblue48a_Eg',
    appId: '1:751293249732:web:ad282c9fd0a744d9ec3191',
    messagingSenderId: '751293249732',
    projectId: 'web-notification-d7e70',
    authDomain: 'web-notification-d7e70.firebaseapp.com',
    storageBucket: 'web-notification-d7e70.appspot.com',
    measurementId: 'G-ME3DPJM3Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2fpk66UvLjPmbGqXZhjJN0eVTQTWRqV8',
    appId: '1:751293249732:android:4b37a91990467e0cec3191',
    messagingSenderId: '751293249732',
    projectId: 'web-notification-d7e70',
    storageBucket: 'web-notification-d7e70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOTbbHRA_ZPfDYIHqe-hS5vl75uthUPA4',
    appId: '1:751293249732:ios:6769b68de8fa964bec3191',
    messagingSenderId: '751293249732',
    projectId: 'web-notification-d7e70',
    storageBucket: 'web-notification-d7e70.appspot.com',
    iosBundleId: 'com.example.flutterWebNotification',
  );
}
